djangoproject/djangoproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('university.urls')),
    path('admin/', admin.site.urls),
]

djangoproject/university/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

urlpatterns = [
    # path('', views.index, name='index'),
    # path('<int:university_id>/', views.university_details, name='university_details'),
    # path('<int:university_id>/update/', views.university_update, name='university_update'),
    path('', views.UniversityListView.as_view(), name='index'),
    path('<int:pk>/', views.UniversityDetailView.as_view(),
         name='university_details'),
    path('<int:pk>/update/', views.UniversityUpdateView.as_view(),
         name='university_update'),
    path('accounts/login/',
         auth_views.LoginView.as_view(template_name='university/login.html'),
         name='login'),
    path('accounts/logout/',
         auth_views.LogoutView.as_view(template_name='university/logout.html'),
         name='logout'),
]

djangoproject/university/models.py
from django.db import models
from django.urls import reverse


class University(models.Model):
    CITY_CHOICES = [
        ('buc', 'Bucharest'),
        ('ias', 'Iași'),
        ('clu', 'Cluj-Napoca'),
    ]
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    city = models.CharField(max_length=3, choices=CITY_CHOICES)

    class Meta:
        verbose_name_plural = 'universities'

    def __str__(self):
        return f'{self.name} ({self.get_city_display()})'

    def get_absolute_url(self):
        return reverse('university_details', args=(self.pk, ))


class Student(models.Model):
    university = models.ForeignKey(University, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    date_enrolled = models.DateField()

    def __str__(self):
        return f'{self.first_name} {self.last_name} ({self.date_enrolled})'

djangoproject/university/forms.py
from django.forms import ModelForm

from .models import University


class UniversityForm(ModelForm):
    class Meta:
        model = University
        fields = ['name', 'city', 'description']

djangoproject/university/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views.decorators.http import require_http_methods, require_GET
from django.views.generic import DetailView, ListView, UpdateView

from .forms import UniversityForm
from .models import University


class UniversityListView(ListView):
    model = University
    context_object_name = 'universities'


class UniversityDetailView(DetailView):
    model = University
    context_object_name = 'university'


class UniversityUpdateView(LoginRequiredMixin, UpdateView):
    model = University
    fields = ['name', 'city', 'description']


@require_GET
def index(request):
    universities = University.objects.all()
    context = {'universities': universities}
    return render(request, 'university/university_list.html', context)


@require_GET
def university_details(request, university_id):
    university = get_object_or_404(University, pk=university_id)
    context = {'university': university}
    return render(request, 'university/university_detail.html', context)


@require_http_methods(["GET", "POST"])
@login_required
def university_update(request, university_id):
    university = get_object_or_404(University, pk=university_id)

    if request.method == 'POST':
        form = UniversityForm(request.POST, instance=university)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(
                reverse('university_details', args=(university.id,)))

    else:
        form = UniversityForm(instance=university)

    context = {'university': university, 'form': form}
    return render(request, 'university/university_form.html', context)

djangoproject/university/templates/university/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
    <meta charset="UTF-8">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    </head>
    <body>
        {% if user.is_authenticated %}
            <p>Logged in as: {{ user.username }} | <a href="{% url 'logout' %}">Log out</a></p>
        {% else %}
            <p><a href="{% url 'login' %}">Log in</a></p>
        {% endif %}

        <div class="page-header">
            <h1><a href="{% url 'index' %}">Universities home</a></h1>
        </div>

        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                {% block content %}
                {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

djangoproject/university/templates/university/index.html
{% extends 'university/base.html' %}

{% block title %}Universities home{% endblock %}

{% block content %}
    {% if universities %}
        <ul class="list-group">
        {% for university in universities %}
            <li class="list-group-item"><a href="{% url 'university_details' university.id %}">{{ university }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No universities are available.</p>
    {% endif %}
{% endblock %}

djangoproject/university/templates/university/login.html
{% extends "university/base.html" %}

{% block content %}

    {% if form.errors %}
        <p>Your username and password didn't match. Please try again.</p>
    {% endif %}

    <form method="post" action="{% url 'login' %}">
        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit" value="login">
        <input type="hidden" name="next" value="{{ next }}">
    </form>

{% endblock %}

djangoproject/university/templates/university/logout.html
{% extends "university/base.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}

    <p>You have successfully logged out.</p>

{% endblock %}

djangoproject/university/templates/university/university_detail.html
{% extends 'university/base.html' %}

{% block title %}University {{ university.name }}{% endblock %}

{% block content %}
    <h4>{{ university }}</h4>
    <p>{{ university.description }}</p>

    {% if user.is_authenticated %}
        <a href="{% url 'university_update' university.id %}">Edit</a>
    {% endif %}

    <ul class="list-group">
        {% for student in university.student_set.all %}
            <li class="list-group-item">{{ student }}</li>
        {% endfor %}
    </ul>
{% endblock %}

djangoproject/university/templates/university/university_details.html
{% extends 'university/base.html' %}

{% block title %}University {{ university.name }}{% endblock %}

{% block content %}
    <h4>{{ university }}</h4>
    <ul class="list-group">
        {% for student in university.student_set.all %}
            <li class="list-group-item">{{ student }}</li>
        {% endfor %}
    </ul>
{% endblock %}

djangoproject/university/templates/university/university_form.html
{% extends 'university/base.html' %}

{% block title %}Edit university {{ university.name }}{% endblock %}

{% block content %}
    <h4>{{ university }}</h4>
    <form action="{% url 'university_update' university.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
{% endblock %}

djangoproject/university/templates/university/university_list.html
{% extends 'university/base.html' %}

{% block title %}Universities home{% endblock %}

{% block content %}
    {% if universities %}
        <ul class="list-group">
        {% for university in universities %}
            <li class="list-group-item"><a href="{% url 'university_details' university.id %}">{{ university }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No universities are available.</p>
    {% endif %}
{% endblock %}

djangoproject/university/templates/university/university_update.html
{% extends 'university/base.html' %}

{% block title %}Edit university {{ university.name }}{% endblock %}

{% block content %}
    <h4>{{ university }}</h4>
    <form action="{% url 'university_update' university.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
{% endblock %}